metadata:
  name: judgement
  description: "查询计划质量评估任务 - 对比两个模型输出判断质量"
  author: "Jieke Wu, SFB Lab, KAUST"
  current_version: "v1"
  tags: ["judgement", "evaluation", "pairwise-comparison", "quality-assessment"]
  notes: |
    该配置用于对比两个不同的模型输出（候选A 和 候选B），
    判断哪一个更接近金标准答案。

    评估维度包括：
    1. 结构完整性（权重：30%）
    2. 语义准确性（权重：40%）
    3. 信息完整度（权重：20%）
    4. 格式规范性（权重：10%）

parameters:
  question:
    type: str
    required: true
    default: null
    description: "用户的原始问题"

  gold_standard:
    type: dict
    required: true
    default: null
    description: "金标准答案（参考答案）"

  candidate_a:
    type: dict
    required: true
    default: null
    description: "候选A 的模型输出"

  candidate_b:
    type: dict
    required: true
    default: null
    description: "候选B 的模型输出"

  evaluation_criteria:
    type: dict
    required: false
    default: null
    description: |
      自定义评估标准，可覆盖默认权重：
      - structure_weight: 结构完整性权重（默认 0.3）
      - semantic_weight: 语义准确性权重（默认 0.4）
      - completeness_weight: 信息完整度权重（默认 0.2）
      - format_weight: 格式规范性权重（默认 0.1）

llm_config:
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 1500
  response_format:
    type: "json_object"

template_mapping:
  v1:
    system: "judgement/judge_system_prompt.jinja2"
    user: null
    description: "基础版本的质量评估 prompt"

output_schema:
  type: "json"
  format: |
    {
      "winner": "candidate_a" | "candidate_b" | "tie",
      "confidence": <float 0.0-1.0>,
      "reason": "<简要说明判断理由，不超过100字>",
      "dimensions": {
        "structure_a": <int 0-10>,
        "structure_b": <int 0-10>,
        "semantic_a": <int 0-10>,
        "semantic_b": <int 0-10>,
        "completeness_a": <int 0-10>,
        "completeness_b": <int 0-10>,
        "format_a": <int 0-10>,
        "format_b": <int 0-10>
      }
    }

evaluation_dimensions:
  structure:
    weight: 0.3
    description: "结构完整性"
    criteria:
      - "JSON 格式是否有效"
      - "必需字段是否完整（domain, sub, is_personal, time, food）"
      - "数据类型是否正确"

  semantic:
    weight: 0.4
    description: "语义准确性"
    criteria:
      - "domain 是否正确识别"
      - "is_personal 判断是否准确"
      - "time 范围是否合理"
      - "query 字段是否准确提取关键信息"

  completeness:
    weight: 0.2
    description: "信息完整度"
    criteria:
      - "是否包含所有金标准中的关键信息"
      - "是否遗漏重要字段"
      - "计划数量是否合理"

  format:
    weight: 0.1
    description: "格式规范性"
    criteria:
      - "日期格式是否规范"
      - "null 值处理是否正确"
      - "整体格式是否清晰"

confidence_levels:
  very_high: [0.9, 1.0]  # 非常确定
  high: [0.7, 0.9]       # 比较确定
  medium: [0.5, 0.7]     # 有一定把握
  low: [0.0, 0.5]        # 不太确定
